dbproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('home.urls'))
]

gacha/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
    url(r'gacha/$',views.gacha.as_view(), name="gacha"),
    url(r'gacha/singlepull/$',views.singlePull.as_view(), name="singlePull"),
    url(r'gacha/multiplepull/$',views.multiplePull.as_view(), name="multiplePull"),
]

home/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
    url(r'^$',views.home.as_view(),name='home'),
    url(r'^project/', include('project.urls', namespace='project')),
    url(r'^gacha/', include('gacha.urls', namespace='gacha')),
]

project/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'bienbox/$',views.s3.as_view(),name='bienbox'),
    url(r'bienbox/create$',views.createS3.as_view(),name='creates3'),
    url(r'bienbox/delete/$',views.deleteBucket.as_view(),name='deleteBucket'),
    url(r'bienbox/bucket/(?P<bucket>\w+)$',views.bucketPage.as_view(),name='bucket'),
    url(r'bienbox/bucket/createFolder/$',views.createFolder.as_view(),name='createFolder'),
    url(r'bienbox/bucket/uploadFile/$',views.uploadFile.as_view(),name='uploadFile'),
    url(r'bienbox/bucket/downloadFile/$',views.downloadFile.as_view(),name='downloadFile'),
    url(r'bienbox/bucket/deleteFile/$',views.deleteFile.as_view(),name="deleteFile"),
    url(r'bienpute/$',views.ec2.as_view(),name='ec2'),
    url(r'architect/$',views.architect.as_view(),name='architect'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class home(TemplateView):
    template_name = 'home/home.html'

home/templates/home/_header.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    {% load staticfiles %}
    <script src="{% static 'scripts/jquery.js' %}"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/grid.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" type="text/css">
  </head>
  <body>
    <div class="header">
      <a href="{% url 'home' %}">
        <h2 id="pixel">DBprojects</h2>
      </a>
    </div>
    {% block content %}
    {% endblock content %}
  </body>
</html>

home/templates/home/home.html
{% include "home/_header.html" %}
{% block content %}
{% load staticfiles %}
<div class="mainPage">
  <div class="projectsHeader">
    <h3>Here are some projects I created.</h3>
  </div>
  <div class="projectsList">
    <ul class="row">
      <li class="col-md-3">
        <a href="{% url 'project:bienbox' %}">
          <img src="{% static 'images/cloudStorage.png' %}" alt="">
          <h4>Simple Cloud Storage</h4>
        </a>
      </li>
      <li class="col-md-3">
        <a href="{% url 'gacha:gacha' %}">
          <img src="{% static 'images/mysqlIcon.png' %}" alt="">
          <h4>Gacha</h4>
        </a>
      </li>
    </ul>
  </div>
</div>
{% endblock content %}