dbproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('home.urls'))
]

gacha/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
    url(r'gacha/$',views.gacha.as_view(), name="gacha"),
    url(r'gacha/singlepull/$',views.singlePull.as_view(), name="singlePull"),
    url(r'gacha/multiplepull/$',views.multiplePull.as_view(), name="multiplePull"),
]

home/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
    url(r'^$',views.home.as_view(),name='home'),
    url(r'^project/', include('project.urls', namespace='project')),
    url(r'^gacha/', include('gacha.urls', namespace='gacha')),
]

gacha/models.py
from django.db import models

# Create your models here.
class Characters(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=45, blank=True, null=True)

    stars = models.IntegerField(blank=True, null=True)
    image = models.CharField(max_length=100, blank=True, null=True)
    series = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'characters'

gacha/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from gacha.models import Characters
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
import random
import json
# Create your views here.
class gacha(TemplateView):
    template_name = 'gacha/gacha.html'

    def randomStar(self):
        selection = [5,4,3]
        probability = [0.03, 0.15, 0.82]
        star = random.choices(selection, probability)
        return star[0]

    '''def get_context_data(self, **kwargs):
        context = super(gacha, self).get_context_data(**kwargs)
        multi = []
        characters = []
        for x in range(5):
            star = self.randomStar()
            multi.append(star)

        for star in multi:
            character = Characters.objects.filter(stars=star).order_by('?')[:1]
            for obj in character:
                characters.append(obj)

        context['characters'] = characters
        context['multi'] = multi
        return context'''


class singlePull(TemplateView):
    template_name = 'gacha/singlepull.html'

    def randomStar(self):
        choice = [5,4,3]
        probability = [0.06, 0.2, 0.80]
        star = random.choices(choice, probability)
        return star


    def post(self, request):
        result = self.randomStar()
        for key in result:
            character = Characters.objects.filter(stars=key).order_by('?')[:1]
            for obj in character:
                name = obj.name
                stars = obj.stars
                series = obj.series
                image = obj.image
        return JsonResponse({'name': name, 'stars': stars, 'series': series, 'image': image}, safe=False)


class multiplePull(TemplateView):
    template_name = 'gacha/multiplePull.html'

    def randomStar(self):
        selection = [5,4,3]
        probability = [0.1, 0.2, 0.7]
        star = random.choices(selection, probability)
        return star[0]

    def post(self, request):
        multi = []
        characters = []
        for x in range(8):
            star = self.randomStar()
            multi.append(star)

        for star in multi:
            charData = {}
            character = Characters.objects.filter(stars=star).order_by('?')[:1]
            for obj in character:
                charData['name'] = obj.name
                charData['series'] = obj.series
                charData['image'] = obj.image
                charData['stars'] = obj.stars
            characters.append(charData)
        return JsonResponse(json.dumps(characters), safe=False)


#Script to add characters to DB
'''image = "no image"
characters = {
    "Auron": {'name': "Auron",
               'stars': 4,
               'image': image,
               'series': "FF10"},
    "Barret": {'name': "Barret",
               'stars': 3,
               'image': image,
               'series': "FF7"},
    "Fran":  {'name': "Fran",
               'stars': 3,
               'image': image,
               'series': "FF12"},
    "Noctis":  {'name': "Noctis",
               'stars': 5,
               'image': image,
               'series': "FF15"},
    "Orlandu":  {'name': "Orlandu",
               'stars': 4,
               'image': image,
               'series': "FFT"},
    "Ramza":  {'name': "Ramza",
               'stars': 5,
               'image': image,
               'series': "FFT"},
    "Rikku":  {'name': "Rikku",
               'stars': 3,
               'image': image,
               'series': "FF10"},
    "Sephiroth":  {'name': "Sephiroth",
               'stars': 4,
               'image': image,
               'series': "FF7"},
    "Terra":  {'name': "Terra",
               'stars': 5,
               'image': image,
               'series': "FF6"},
    "Tidus":  {'name': "Tidus",
               'stars': 5,
               'image': image,
               'series': "FF10"},
    "Tifa":  {'name': "Tifa",
               'stars': 4,
               'image': image,
               'series': "FF7"},
    "Vivi":  {'name': "Vivi",
               'stars': 3,
               'image': image,
               'series': "FF9"},
    "Wakka":  {'name': "Wakka",
               'stars': 3,
               'image': image,
               'series': "FF10"},
    "Yuffie":  {'name': "Yuffie",
               'stars': 3,
               'image': image,
               'series': "FF7"},
    "Zidane":  {'name': "Zidane",
               'stars': 5,
               'image': image,
               'series': "FF9"}
}
for key, value in characters.items():
    number = 3
    name = value['name']
    stars = value['stars']
    image = value['image']
    series = value['series']
    Characters.objects.create(id=number,name=name,stars=stars,image=image,series=series)
    number += 1
'''

gacha/templates/gacha/gacha.html
{% include "home/_header.html" %}
{% block content %}
{% load staticfiles %}
<div class="mainPage">
  <div class="gachaHeader">
    <h5 style="float: left; padding: 0.3em 0.5em;"><a href="{% url 'home' %}"><< Back</a></h5>
    <h3>Gacha Simulator</h3>
  </div>
  <div class="explanation">
    <h5 id='clickable'>Click here to see/hide description</h5>
    <div class="description">
      <h3>What is a Gacha game?</h3>
      <h5>Gacha game refer to games that utilize the Gacha mechanism (loot box) to
        monetise. Most of these games are freemium. In these games, there are usually
        numerous characters, cards, or other items that players can obtain, and most
        of them are only obtainable via the "gacha" mechanism. The "gacha" mechanism
        would allow players to "spin" the gacha using a specific amount of in-game
        currency, which would give player a randomised character or item. Sometimes,
         these gacha would be limited, such that those characters and items can only
         be obtained within a specific event time frame. Because some of these items
         or characters would be given less chance to appear, typically players would
         need to spin the gacha many times before they can get the most desired outcome.
         In these games, gacha could be essential for players to make progress in the game.
         Players may be given free or discounted gachas, but have to pay to get more.
         These games may also feature different tiers of gacha pulls, which give different sets of rewards.
      </h5>
      <h5>In this simulator I'm recreating the spin mechanism with which the player can
        obtain characters. I have chosen characters from Final Fantasy games as this
        is my favourite series. The characters are ranked by the number of stars.
      </h5>
      <ul id='explanation'>
        <li><h5>5 stars is the rarest type and I set a 3%(6% with multi pull) chance of getting such character.</h5></li>
        <li><h5>4 stars have 15%(20% with multi pull) of being pulled.</h5></li>
        <li><h5>3 stars characters are the most common and they have 82%(80% with multi pull) of being pulled.</h5></li>
      </ul>
      <h5>Below are buttons for either a single character pull or 10 character pull.
      The probability doesn't change with multi pull(as is often a case in gacha games).
      Have fun!
    </h5>
    </div>
    <div class="pullButton container">
      <ul class="row" >
        <li class="col">
          <form class="singleForm" method="post">
            <button type="submit" class="btn btn-primary">Single Pull</button>
          </form>
        </li>
        <li class="col">
          <form class="multipleForm" method="post">
            <button type="submit" class="btn btn-success">Multi Pull</button>
          </form>
        </li>
      </ul>
    </div>
    <div class="resetButton" style="text-align: center;">
      <button type="button" class="reset btn btn-danger">Reset</button>
    </div>
    <div class="gachaResults">
      <div class="resultsHeader">
        <h4>Results</h4>
      </div>
      <div class="container">
        <div class="row">
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $('#clickable').on('click', function(){
    $('.explanation .description').toggle(1000);
  });
function reset(){
  $('.container .row .col-md-3').remove();
}
  $('.singleForm').on('submit', function(e){
    e.preventDefault();
    reset();
      $.ajax({
      url: "{% url 'gacha:singlePull' %}",
      type: 'post',
      data: {'data': true, csrfmiddlewaretoken: '{{ csrf_token }}'},
      success: function(result) {
        var stars = result.stars;
        var link = $('<div class="col-md-3"><div class="charHeader"><h5>' + result.series +
        '</h5></div><img class="charImg" src="'+ result.image +'" alt="" /><div class="charDetails"><h5>'
         + result.name + '</h5><h6 class="stars'+ stars +'"></h6></div></div>');
        $('.gachaResults .container .row').append(link);
        $('body').scrollTo('.row');
      }
    });
  });
  $('.multipleForm').on('submit', function(e){
    e.preventDefault();
    reset();
    $.ajax({
      url: "{% url 'gacha:multiplePull' %}",
      type: 'post',
      data: {'data': true, csrfmiddlewaretoken: '{{ csrf_token }}'},
      success: function(result) {
            $.each(JSON.parse(result), function(key, value){
              var stars = value.series;
              var link = $('<div class="col-md-3"><div class="charHeader"><h5>' + value.series +
              '</h5></div><img class="charImg" src="'+ value.image +'" alt="" /><div class="charDetails"><h5>'
               + value.name + '</h5><h6 class="stars'+ value.stars +'"></h6></div></div>');
              $('.gachaResults .container .row').append(link);
            });
      }
    });
  });
  $('.reset').on('click', function(){
      reset();
  });
</script>
{% endblock content %}