dbproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('home.urls'))
]

home/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
    url(r'^$',views.home.as_view(),name='home'),
    url(r'^project/', include('project.urls', namespace='project')),
    url(r'^gacha/', include('gacha.urls', namespace='gacha')),
]

project/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'bienbox/$',views.s3.as_view(),name='bienbox'),
    url(r'bienbox/create$',views.createS3.as_view(),name='creates3'),
    url(r'bienbox/delete/$',views.deleteBucket.as_view(),name='deleteBucket'),
    url(r'bienbox/bucket/(?P<bucket>\w+)$',views.bucketPage.as_view(),name='bucket'),
    url(r'bienbox/bucket/createFolder/$',views.createFolder.as_view(),name='createFolder'),
    url(r'bienbox/bucket/uploadFile/$',views.uploadFile.as_view(),name='uploadFile'),
    url(r'bienbox/bucket/downloadFile/$',views.downloadFile.as_view(),name='downloadFile'),
    url(r'bienbox/bucket/deleteFile/$',views.deleteFile.as_view(),name="deleteFile"),
    url(r'bienpute/$',views.ec2.as_view(),name='ec2'),
    url(r'architect/$',views.architect.as_view(),name='architect'),
]

project/models.py
from django.db import models

# Create your models here.

project/forms.py
from django import forms

##Create S3 bucket forms
class S3Form(forms.Form):
    name = forms.CharField()

project/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView,ListView,DeleteView,CreateView
from django.core.urlresolvers import reverse_lazy
from django.core import serializers
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
import boto3
from .forms import S3Form
import os
import time
import datetime
# Create your views here.
def file_size(num, suffix="B"):
    for unit in ['','K','M','G','T','P','E']:
        if abs(num) < 1024.0:
            return "%3.1f%s%s" % (num, unit, suffix)
        num /= 1024.0
    return "%.1f%s%s" % (num, "Yi", suffix)

class s3(TemplateView):
    template_name = 'project/s3.html'
    def get_context_data(self, **kwargs):
        context = super(s3, self).get_context_data(**kwargs)
        data = []
        aws = boto3.resource('s3')
        buckets = aws.buckets.all()
        #Get data from each bucket
        for bucket in buckets:
            bucketData = {}
            totalSize = 0
            bucketName = bucket.name
            if bucketName != "dbgachaimages2":
                fileBuckets = boto3.resource('s3').Bucket(bucketName)
                #Get data for each object inside each bucket
                for file in fileBuckets.objects.all():
                    totalSize += file.size
                bucketData['bucketName'] = bucket.name
                bucketData['createdAt'] = bucket.creation_date
                bucketData['totalSize'] = file_size(totalSize)
                data.append(bucketData)
        context['buckets'] = data
        return context

class createS3(TemplateView):
    template_name = 'project/create_s3.html'

    def createBucket(self, bucketName):
        s3 = boto3.resource('s3')
        s3.create_bucket(Bucket=bucketName, CreateBucketConfiguration={'LocationConstraint': "eu-west-2"})

    def post(self, request):
        bucketName = request.POST.get("newBucketName")
        self.createBucket(bucketName)
        return JsonResponse("ok", safe=False)

#///////////
class deleteBucket(TemplateView):
    template_name = "project/delete_bucket.html"

    def deleteBucket(self, name):
        s3 = boto3.resource('s3')
        bucket = s3.Bucket(name)
        for object in bucket.objects.all():
            object.delete()
        bucket.delete()

    def post(self, request):
        bucketName = request.POST.get("deleteBucket")
        self.deleteBucket(bucketName)
        return JsonResponse(bucketName, safe=False)

class bucketPage(TemplateView):
    template_name = "project/bucket.html"

    def get_context_data(self, *args, **kwargs):
        context = super(bucketPage, self).get_context_data(**kwargs)
        bucketName = self.kwargs['bucket']

        #Display all items
        s3 = boto3.resource('s3')
        bucket = s3.Bucket(bucketName)
        objects = bucket.objects.all()
        data = []
        totalSize = 0
        for object in objects:
            fileData = {}
            fileName = object.key
            size = object.size
            fileSize = file_size(object.size)
            modified = object.last_modified
            fileData['fileSize'] = fileSize
            fileData['fileName'] = fileName
            fileData['modified'] = modified
            totalSize += size
            data.append(fileData)
        context['bucketName'] = bucketName
        context['totalSize'] = totalSize
        context['convertedSize'] = file_size(totalSize)
        context['objects'] = data
        return context

class createFolder(TemplateView):
    template_name = "project/createFolder.html"

    def post(self, request):
        folderName = request.POST.get('folderName')
        bucketName = request.POST.get('bucketName')
        self.newFolder(bucketName, folderName)
        return JsonResponse("Folder Created!", safe=False)

    def newFolder(self, bucket, folder):
        aws = boto3.client('s3')
        aws.put_object(Bucket=bucket,
                       Body='',
                       Key=folder + "/")

class uploadFile(TemplateView):
    template_name = "project/uploadFile.html"

    def uploadFileToS3(self, fileData, bucket, fileName):
        s3 = boto3.resource('s3')
        bucket = s3.Bucket(bucket)
        bucket.put_object(Key=fileName, Body=fileData)

    def post(self, request):
        fileName = request.POST.get('fileName')
        bucket = request.POST.get('bucket')
        fileData = request.FILES['file']
        self.uploadFileToS3(fileData, bucket, fileName)
        return JsonResponse("Good", safe=False)

class downloadFile(TemplateView):
    template_name = "project/downloadFile.html"

    def post(self, request):
        fileName = request.POST.get('fileName')
        bucketName = request.POST.get('bucketName')
        presignedUrl = self.downloadFile(bucketName, fileName)
        return JsonResponse(presignedUrl, safe=False)

    def downloadFile(self, bucket, fileToDownload):
        s3 = boto3.client('s3')
        url = s3.generate_presigned_url('get_object', Params = {'Bucket': bucket,
                                  'Key': fileToDownload}, ExpiresIn = 100)
        return url

class deleteFile(TemplateView):
    template_name = "project/deleteFile.html"

    def post(self, request):
        fileName = request.POST.get('fileName')
        bucketName = request.POST.get('bucketName')
        self.fileDelete(bucketName, fileName)
        return JsonResponse("Deleted", safe=False)

    def fileDelete(self, bucket, fileName):
        s3 = boto3.resource('s3')
        s3.Object(bucket, fileName).delete()

class ec2(TemplateView):
    template_name = 'project/ec2.html'
class architect(TemplateView):
    template_name = 'project/architect.html'

project/templates/project/architect.html
{% include "home/_header.html" %}
{% block content %}
{% load staticfiles %}
<div class="s3">
  arch
</div>
{% endblock content %}

project/templates/project/bucket.html
{% include "home/_header.html" %}
{% block content %}
{% load staticfiles %}
<div class="mainPage">
  <div class="objectWrapper">

    <div id='buckName'>
      <a href="{% url 'project:bienbox' %}"><h6><-- Back</h6></a>
      <h5>{{ bucketName }}</h5>
    </div>
    <h4>total size: {{ convertedSize }}</h4>
    <input type="hidden" id="totalSize" value="{{ totalSize }}">
    <hr>
    <div class="bucketCreateOptions">
      <ul id="inline-block">
        <!--This link can create a new folder howerver I do not plan on implementing this yet. Maybe sometime in the future -->
        <!--<li><button type="button" class="button create" id='newFolder'>New Folder</button></li>-->
        <li>
          <form class="uploadForm" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="button" class="btn btn-info" id="upload" value="Choose a file">
            <input type="file" id="uploadFile">
            <input type="submit" class="btn btn-primary" id="uploadButton" value="Upload">
          </form>
        </li>
      </ul>
      <div class="progress">
        <div id="progressBar" class="progress-bar" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">0%</div>
      </div>
    </div>
    <div class="bucketFileList">
      <ul id="inline-block">
        <div id="name">
          <li>Name</li>
        </div>
        <div id="rest">
          <li>Modified</li>
          <li>Size</li>
          <li>Options</li>
        </div>
        <div class="clear"></div>
      </ul>
    </div>
    <div class="objectsList">
        <ul>
          <form method="post" class="createFolder">{% csrf_token %}</form>
          {% if objects %}
          {% for object in objects %}
          <li id='mainLi'>
            <div class="fileName">{{ object.fileName }}</div>
            <div id="rest" class="menuu">
              <ul>
                <li id='topLevel'>{{ object.modified|date:"d/m/Y" }}</li>
                <li id='topLevel'>{{ object.fileSize }}</li>
                <li id='menuIcon'>
                  <ul class='dropdownMenu'>
                    <li>
                      <form class="downloadForm" method="post">
                        {% csrf_token %}
                          <h6 id='DownloadButton'>Download</h6>
                      </form>
                    </li>
                    <li>
                      <form class="deleteForm" method="post">
                        {% csrf_token %}
                          <h6 id='DeleteButton'>Delete</h6>
                      </form>
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
          </li>
          <div class="clear">
          </div>
          {% endfor %}
      {% else %}
          <h5>There are no files in this storage yet</h5>
      {% endif %}
      </ul>
    </div>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){
/*Open a submenu when clicking on menu icon*/
$('.menuu ul').on('click', function(){
  var size = $(this).find('#menuIcon ul').toggle();
});
/*Trigger file upload on a button click*/
$('#upload').on('click', function(){
  $('#uploadFile').trigger('click');
  $('#uploadButton').show();
});
/*Creating a new folder will not be implemeted now*/
/*Counter for number of new folder fields. Only one field can be displayed at a time*/
var counter = 0;
/*Generates a text field to enter the name for a new folder*/
$('#newFolder').click(function(){
  var newFolderLine = $('<li><input type="checkbox" class="styled-checkbox"><div id="name"><input type="text" id="folderName" /></div></li>');
  /*Allow only one folder name field be displayed at a time*/
  if(counter == 0) {
    $('.createFolder').append(newFolderLine);
    counter += 1;
  } else {
    alert("Please name the current folder");
  }
});
/*Create a new folder with the information entered earlier.*/
/*This will not be implemented yet*/
/*$('.createFolder').on('submit', function(event){
  event.preventDefault();
  var folderName = $('#folderName').val();
  var buckName = $('#buckName').html();
  $.ajax({
    url: '{% url 'project:createFolder' %}',
    type: 'post',
    data: {
      'folderName': folderName,
      'bucketName': buckName,
      csrfmiddlewaretoken: '{{ csrf_token }}'
    },
    dataType: 'json',
    success: function(data) {
      alert(data);
      location.reload();
    }
  });
});*/
/*###################################################################*/
/*File size conversion function*/
function sizeConverter(size, decimals) {
  if(size == 0) return '0 Bytes';
  var k = 1024;
  var sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];
  var i = Math.floor(Math.log(size) / Math.log(k));
  var dm = decimals || 2;
  var i = parseInt(Math.floor(Math.log(size) / Math.log(1024)));
  return parseFloat((size / Math.pow(k, i)).toFixed(dm)) + ' ' + sizes[i];
}
/*Upload Progress Bar*/

/*###################################################################*/
/*Upload file*/
$('.uploadForm').on('submit', function(event){
  event.preventDefault();
  var fileSize = $('#uploadFile')[0].files[0].size;
  var fileName = $('#uploadFile')[0].files[0].name;
  var realSize = sizeConverter(fileSize, 2);
  var uploadFile = $('#uploadFile')[0].files[0];
  var buckName = $('#buckName h5').html();
  var totalSize = parseFloat($('#totalSize').val());
  var limit = fileSize + totalSize;
  var fileData = new FormData();
  fileData.append('fileSize', realSize);
  fileData.append('fileName', fileName);
  fileData.append('file', uploadFile);
  fileData.append('bucket', buckName);
  fileData.append('csrfmiddlewaretoken', '{{ csrf_token }}');
  //Check if 4GB limit has been reached or not
  if(limit > 4294967296) {
    alert("You have reached the 4GB limit. You can't upload any more files");
  } else {
    $('.progress').css('visibility', 'visible');
    $.ajax({
      xhr: function(){
        var xhr = new window.XMLHttpRequest();
        xhr.upload.addEventListener('progress', function(e){
            if(e.lengthComputable) {
              var percent = Math.round((e.loaded / e.total) * 100);
              $('#progressBar').attr('aria-valuenow', percent).css('width', percent + "%").text(percent + "%");
            }
        });
        return xhr;
      },
      url: "{% url 'project:uploadFile' %}",
      type: 'post',
      data: fileData,
      cache: false,
      processData: false,
      contentType: false,
      success: function(data){
        location.reload();
      }
    });
  }
});
/*##############################################################*/
//Trigger form submission
$('.objectsList ul #DownloadButton').on('click', function(){
  $(this).parents('.deleteForm').submit();
});
/*Download file*/
$('.downloadForm').on('click', function(e){
  e.preventDefault();
  var buckName = $('#buckName h5').html();
  var fileName = $(this).parents('#mainLi').find('.fileName').html();
  var data = {'bucketName': buckName,
              "fileName": fileName,
              csrfmiddlewaretoken: '{{ csrf_token }}'}
    $.ajax({
    url: "{% url 'project:downloadFile' %}",
    type: 'post',
    data: data,
    dataType: 'json',
    success: function(data){
      window.location = data;
    }
  });
});
/*##############################################################*/
//Trigger form submission
$('.objectsList ul #DeleteButton').on('click', function(){
  $(this).parents('.deleteForm').submit();
});
/*Delete file*/
$('.deleteForm').on('submit', function(e){
  e.preventDefault();
  var buckName = $('#buckName h5').html();
  var fileName = $(this).parents('#mainLi').find('.fileName').html();
  $.ajax({
    url: "{% url 'project:deleteFile' %}",
    type: 'post',
    data: {'bucketName': buckName,
           "fileName": fileName,
           csrfmiddlewaretoken: '{{ csrf_token }}'},
    dataType: 'json',
    success: function(data) {
      location.reload();
      }
    });
  });
});
</script>
{% endblock content %}

project/templates/project/deleteFile.html
yo!

project/templates/project/ec2.html
{% include "home/_header.html" %}
{% block content %}
{% load staticfiles %}
<div class="s3">
  ec2
</div>
{% endblock content %}

project/templates/project/s3.html
{% include "home/_header.html" %}
{% block content %}
{% load staticfiles %}
<div class="mainPage">
  <div class="s3Wrapper">
    <h5 style="float: left;"><a href="{% url 'home' %}"><< Back</a></h5>
    <br>
    <div class="explanation">
      <h5 id='clickable'>Click here to see/hide description</h5>
      <div class="description">
        <h5>In this project I created a simple storage service in Cloud. Users can
          upload/download to and delete files from storage drives. I limited the number
          of drives to three and put a limit of maximum 4GB on each of them.
          I plan on improving this in the near future to add more functions like
          creating folders or multiple file upload/download feature.
        </h5>
      </div>
    </div>
    <div class="descriptionBar">
      <div id="left">
        <h4 id='boxName'>Name</h4>
      </div>
      <div id="right">
        <ul id='descExtra'>
          <li>Created on</li>
          <li>Space</li>
          <li>Options</li>
        </ul>
      </div>
    </div>
    <div class="s3Items">
      {% for bucket in buckets %}
      <div class="s3Name">
        <div id="left">
          <a href="{% url 'project:bucket' bucket=bucket.bucketName %}"><h4 class='s3ItemName'>{{ bucket.bucketName }}</h4></a>
        </div>
        <div id="right">
          <ul id='s3ItemDesc'>
            <li>{{ bucket.createdAt|date:"d/m/Y" }}</li>
              <li>{{ bucket.totalSize }}/4GB</li>
            <li>
              <form method="post" class="bucketDeleteForm">
                {% csrf_token %}
                <button type="submit" class='btn btn-danger'>Delete</button>
              </form>
            </li>
          </ul>
        </div>
    </div>
    {% endfor %}
    <form method="post" class="newBucketform">
       {% csrf_token %}
    </form>
  </div>
  <button class="button create">Create</button>
  <div id="numberBuckets">
  </div>
</div>
<script type="text/javascript">
  $('#clickable').on('click', function(){
    $('.explanation .description').toggle(1000);
  });
  var counter = 0; //Counter to check how many buckets have been created. 3 is max.
  var numBuckets = $('.s3Name').length; //How many buckets are currently created.
  //Function to create a new input field to name a new bucket
  $('#numberBuckets').html("<h5>Buckets: " + numBuckets + "/3</h5>");
  $('.create').on('click', function(){
    if(numBuckets < 3) {
      if(counter == 0) {
        var newBucketInput = $('<input id="newBucketName" type="text"  />');
        $('.newBucketform').append(newBucketInput);
        counter += 1;
      } else {
        alert("Please name the new bucket");
      }
    } else {
      alert("You can create maximum 3 buckets");
    }
  });
  //A function to create a new bucket
  $('.newBucketform').on('submit', function(e){
    e.preventDefault();
    var newBucketName = $('#newBucketName').val();
    if(newBucketName == "") {
      alert("Please enter bucket name");
    }
    else
    {
      $.ajax({
        url: "{% url 'project:creates3' %}",
        type: 'post',
        data: {'newBucketName': newBucketName, csrfmiddlewaretoken: '{{ csrf_token }}'},
        dataType: 'json',
        success: function(data){
          location.reload();
        }
      });
    }
  });
  //Delete a bucket
  $('.bucketDeleteForm').on('submit', function(e){
    e.preventDefault();
    var bucketName = $(this).parents('.s3Name').find('h4').html();

    $.ajax({
      url: "{% url 'project:deleteBucket' %}",
      type: 'post',
      data: {'deleteBucket': bucketName, csrfmiddlewaretoken: '{{ csrf_token }}'},
      dataType: 'json',
      success: function(data){
        location.reload();
      }
    });
  });
</script>
{% endblock content %}